import Head from 'next/head'
import Link from 'next/link'
import Form2 from '../component/Form2'
import Gallery from '../component/Gallery'
import Increase from '../component/Increase'
import Input from '../component/Input'
import Sidebar from '../component/Sidebar'
import { wrapper } from '../features/store'
import ViewTable from './ViewTable'
import styles from '../styles/Home.module.css'
//import Navbar from '../component/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    <Form2/>
    <Link href='/ViewTable'>viewtable</Link>
     <Gallery/>
     <Input/>
     <Increase/>
   
    </div>
  )
}
